version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./packages/backend
    container_name: todo_backend
    restart: always
    ports:
      - '4000:4000'
    volumes:
      - ./packages/backend:/app
    depends_on:
      - mysql

  frontend:
    build: ./packages/frontend
    container_name: todo_frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./packages/frontend:/app
    depends_on:
      - backend

volumes:
  mysql_data:
    driver: local
